[features]
seeds = false
skip-lint = false
[programs.localnet]
bet_game = "DAconAbZXm7EPoWW5WK9uwhsunkLSSw8n1ZBpDX6KFE9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nilav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
